### ISSUE TITLE
What about other providers?

### ISSUE THREAD

**Issue by uikolas** [jasonroman/nba-api#1]
As i see, it is uses just one endpoint to get stats? 
https://github.com/jasonroman/nba-api/blob/master/src/Request/Stats/AbstractStatsRequest.php#L9

But What about for example [this one](http://data.nba.net/10s/prod/v1/today.json) if i want to use this endpoint? Can it be changed somehow? Or Request classes does not support it?

**Comment by jasonroman** [comment]
Hello,

There are endpoints from 6 different domains.  If you look in the Request directory, you will see 6 sub-directories.  Each one of those points to a different domain.  For instance, the endpoint you are looking for is found in this request class:

https://github.com/jasonroman/nba-api/blob/master/src/Request/Data/Prod/General/TodayRequest.php

That request extends a base Data class found here:  https://github.com/jasonroman/nba-api/blob/master/src/Request/Data/AbstractDataRequest.php#L13

You can also check nbasense.com for a full reference aside from sifting through the code.  Let me know if that helps!

**Comment by uikolas** [comment]
Oh, now I get it. But it confuses a little bit. :)

But what about making one request for player stats for example? And just pass enpoint (or class which implements specific interface).

For example:
```
$request = new PlayerRequest(new NbaDataProvider()); (or new NbaStatsProvider())
$client->request($request);
```
I know that not all endpoints returns player stats.

**Comment by jasonroman** [comment]
I'd love to help but I am not exactly sure what you are asking. Could you clarify? The way I designed this is to have a single request per endpoint. The reason for this is each endpoint is very different in the options you can pass to it and the results that are returned. Many player stats endpoints, for example, use the same parameters but they don't always share the same valid options for those parameters.

I think reading through http://nbasense.com/nba-api/requests will give you a more thorough understanding of the structure.

**Comment by uikolas** [comment]
Nevermind. Yes, you are correct. Each endpoint returns different results.
